spring:
  application:
    name: discovery-service

server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true