spring:
  application:
    name: application-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: ${PORT:9000}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
